// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gkavnjbnucmcxrxiluvv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdrYXZuamJudWNtY3hyeGlsdXZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczODUxMjEsImV4cCI6MjA2Mjk2MTEyMX0.gE7tT-H_5cRb6U4D1lS4uRhwjBk5ih_mntKX6Ttt0QE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);